[tool.poetry]
name = "popnas"
version = "0.1.0"
description = "POPNAS algorithm"
authors = ["AndreaFalanti <a.falanti@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "3.6.9"
sklearn = "^0.0"
tensorflow = "^2.6.0rc0"
pandas = ">=0.25.2"
tqdm = ">=4.32.1"
xgboost = ">=0.90"
mlxtend = "^0.18.0"
matplotlib = ">=3.1.1"
eli5 = "^0.11.0"
mypy = "^0.910"

[tool.poetry.dev-dependencies]
autopep8 = "^1.5.7"
pylint = "^2.9.6"
flake8 = "^3.9.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.autopep8]
max_line_length = 150
in-place = true
recursive = false